---
dist: bionic
os: ["linux"]
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3
git:
  submodules: true
install:
  - python -m pip install coveralls
  - make _deps
script:
  - make _test
  - coveralls
