---
dist: xenial
os: ["linux"]
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.8
  - 3.9
  - pypy3
cache: pip
git:
  submodules: true

install:
  - python -m pip install coveralls
  - python -m pip install colorama==0.4.1
  - python -m pip install coverage>=4.5.4
  - python -m pip install -r requirements.txt
  - python -m pip install -r requirements-test-win_xp-ubu1604.txt

script:
  - make _test
  - if [[ "$(python --version)" =~ "3.6." && "$(which pypy)" == "" ]]; then coveralls; fi
