---
dist: xenial
os: ["linux"]
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.8
  - 3.9
  - pypy3
cache: pip
git:
  submodules: true

install:
  - python -m pip install coveralls
  - python -m pip install colorama==0.4.1
  - make _deps

script:
  - make _test
  - if [[ "$(python --version)" =~ "3.6." && "$(which pypy)" == "" ]]; then coveralls; fi
