#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# PYTHON_ARGCOMPLETE_OK
"""
Created on Fri Sep 28 22:25:38 2018

@author: gamesguru
"""

import sys

from ntclient.__main__ import main

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
