---
name: install-linux

"on":
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  python:
    runs-on: [ubuntu-20.04]

    strategy:
      matrix:
        python-version: ["3.11", "3.5"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # update-environment: false
          # NOTE: fails on Python 3.6 and 3.4 with the pip error,
          #   ERROR: unknown command "cache" - maybe you meant "check"
          # cache: "pip" # caching pip dependencies
          # cache-dependency-path: "**/requirements*.txt"

      # NOTE: see above NOTE, we are still using deprecated cache restore
      - name: Reload Cache / pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # NOTE: only cares about base requirements.txt
          # yamllint disable rule:line-length
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
          # yamllint enable rule:line-length
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install CLI
        env:
          PY_SYS_INTERPRETER: python3
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n --version
          nutra --debug recipe init -f
          nutra --no-pager recipe
