---
name: install-win32

"on":
  push:
    branches:
      # TODO: only run on master, it's slow (or just make unrequired check?)
      - "**"

jobs:
  python:
    runs-on: [windows-latest]

    strategy:
      matrix:
        python-version: ["3.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # update-environment: false

      - name: Reload Cache / pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          # NOTE: only cares about base requirements.txt
          # yamllint disable rule:line-length
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
          # yamllint enable rule:line-length
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install CLI
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n --version
          nutra --debug init -y
          nutra --no-pager nt
          nutra --no-pager sort -c 789
          nutra --no-pager search ultraviolet mushrooms
          nutra --no-pager anl 9050
          nutra --no-pager recipe
          nutra day tests/resources/day/human-test.csv
