---
name: install-linux

"on":
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  python:
    runs-on: [ubuntu-18.04]

    strategy:
      matrix:
        python-version: ["3.4", "3.6", "3.8", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }} & Restore Cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # update-environment: false
          # NOTE: fails on Python 3.6 and 3.4 with the pip error,
          #   ERROR: unknown command "cache" - maybe you meant "check"
          # cache: "pip" # caching pip dependencies
          # cache-dependency-path: "**/requirements*.txt"

      # NOTE: see above NOTE, we are still using deprecated cache restore
      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install CLI
        env:
          PY_SYS_INTERPRETER: python3
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n -v
          nutra -d recipe init
          nutra --no-pager recipe
