---
name: install-win32

"on":
  push: {}

jobs:
  windows-latest:
    runs-on: windows-latest

    steps:
      - name: Configure Line Endings / git / LF
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n -v
          nutra --no-pager recipe
