---
name: install-linux

"on":
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  python:
    runs-on: [ubuntu-18.04]

    strategy:
      matrix:
        python-version: ["3.4", "3.6", "3.8", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }} & Restore Cache
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements*.txt"
          update-environment: false

      - name: Install CLI
        env:
          PY_SYS_INTERPRETER: python3
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n -v
          nutra -d recipe init
          nutra --no-pager recipe
