---
name: test-linux
"on":
  push: {}

jobs:
  test-linux:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: ["3.4.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        # NOTE: container lacks OS dist for testresources/launchpadlib
        run: |
          python -m pip install --upgrade pip
          # NOTE: use the old install file for Python 3.4
          #  these are the latest versions on GitHub for Python 3.4
          pip install colorama==0.4.1
          pip install -r requirements.txt

      - name: Install
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n -v
          nutra -d init -y
          nutra --no-pager nt
          nutra --no-pager sort -c 789
          nutra --no-pager search ultraviolet mushrooms
          nutra --no-pager anl 9050
          nutra --no-pager recipe
          nutra day tests/resources/day/human-test.csv
