---
name: CI
"on":
  push: {}

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        # NOTE: container lacks OS dist for testresources/launchpadlib
        run: |
          pip install testresources==2.0.1
          make _deps

      - name: Lint
        run: make _lint

      # TODO: Tests for: python-argcomplete (tab-completion)
      - name: Test
        run: make _test

  # Windows integration tests: Makefile, pip, and lint/test
  test-win32:
    runs-on: windows-latest

    steps:
      - name: Configure Line Endings / git / LF
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: make _deps

      # NOTE: Skip this on Windows, they are on different drives.
      #  It errors on copying over ~/.nutra/nt.sqlite3
      #  We can modify NUTRA_HOME for the tests,
      #    or we can test `make install` and `nutra init` directly.
      # - name: Run Tests
      #   run: make _test

      - name: Run linters
        run: make _lint

      - name: Install
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n -h
          nutra
          nutra init -y
          nutra nt
          nutra sort -c 789
          nutra search ultraviolet mushrooms
          nutra anl 9050
          nutra recipe
