---
name: test

"on": push

permissions:
  contents: read

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # NOTE: disabled for now, GitHub hosted doesn't ship with it
      # - name: Count lines of code
      #   run: make extras/cloc

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Install requirements
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # NOTE: disabled for now, GitHub hosted is already an isolated env
      # - name: Initialize (venv)
      #   run: make init

      - name: Install requirements
        run: >
          python3 -m pip install
          coveralls
          -r requirements.txt
          -r requirements-test.txt

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Test
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Test
        run: make _test

      - name: Submit coverage report / coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
