---
name: test

"on": push

permissions:
  contents: read

jobs:
  test:
    runs-on: [self-hosted, dev]

    env:
      SKIP_VENV: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Count lines of code
        run: make extras/cloc

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Install requirements
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Initialize (venv)
        run: make init

      - name: Install requirements
        run: >
          source .venv/bin/activate &&
          python3 -m pip install
          coveralls
          -r requirements.txt
          -r requirements-test.txt

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Test
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Test
        run: source .venv/bin/activate && make test

      - name: Submit coverage report / coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
