---
name: test

"on":
  push: {}

jobs:
  test:
    runs-on: [self-hosted, dev-east]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cloc
        run: make extras/cloc

      - name: Install requirements
        run: |
          /usr/bin/python3 -m pip install -r requirements.txt
          /usr/bin/python3 -m pip install -r requirements-test.txt

      - name: Test
        run: PATH=~/.local/bin:$PATH make _test

      - name: Submit coverage report / coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: PATH=~/.local/bin:$PATH coveralls --service=github
