---
name: test

"on": push

permissions:
  contents: read

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # NOTE: disabled for now, GitHub hosted doesn't ship with it
      # - name: Count lines of code
      #   run: make extras/cloc

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Install requirements
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Initialize (venv)
        run: make init

      - name: Install requirements
        run: |
          python3 -m pip install coveralls
          source .venv/bin/activate
          make deps

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # Test
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - name: Test
        run: source .venv/bin/activate && make test

      - name: Submit coverage report / coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
