---
name: test-linux

"on":
  push: {}

jobs:
  python:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: ["3.4.10", "3.6", "3.8", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # NOTE: These are the last supported versions on Python 3.4
      - name: Install requirements (Python 3.4)
        if: matrix.python-version == '3.4.10'
        run: |
          pip install colorama==0.4.1

      - name: Install CLI
        env:
          PY_SYS_INTERPRETER: python3
        run: make install

      - name: Basic Tests / CLI / Integration
        run: |
          n -v
          nutra -d init -y
          nutra --no-pager nt
          nutra --no-pager sort -c 789
          nutra --no-pager search ultraviolet mushrooms
          nutra --no-pager anl 9050
          nutra --no-pager recipe
          nutra day tests/resources/day/human-test.csv
